### ISSUE TITLE
Offer only valid team_ids

### ISSUE THREAD

**Issue by harti2006** [zalando-stups/yourturn#454]
The current team_id-selectbox options within application/edit form, offer AWS account ids instead of team ids. However if one selects a team, that is not recognized by the teams API, the process of creating service users for the application will fail.

Please offer only valid team ids. Hint: The "owner" of the aws accounts could be used as possible options.

**Comment by prayerslayer** [comment]
:+1: * 1000

There is also an API for teams we use anyways. However the reason for showing accounts instead of teams was that back in the days freelancers then couldn't e.g. push docker images to the team's namespace because they were organizationally not part of the team. Before implementing this we have to double-check what it means for our services.
